# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SearchEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SemanticSearch = channel.unary_unary(
                '/swiftsearch.SearchEngine/SemanticSearch',
                request_serializer=service__pb2.SearchRequest.SerializeToString,
                response_deserializer=service__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.IndexTargetFolder = channel.unary_unary(
                '/swiftsearch.SearchEngine/IndexTargetFolder',
                request_serializer=service__pb2.IndexRequest.SerializeToString,
                response_deserializer=service__pb2.IndexResponse.FromString,
                _registered_method=True)
        self.GetSystemStatus = channel.unary_unary(
                '/swiftsearch.SearchEngine/GetSystemStatus',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UpdateSettings = channel.unary_unary(
                '/swiftsearch.SearchEngine/UpdateSettings',
                request_serializer=service__pb2.SettingsRequest.SerializeToString,
                response_deserializer=service__pb2.SettingsResponse.FromString,
                _registered_method=True)
        self.PreloadModel = channel.unary_unary(
                '/swiftsearch.SearchEngine/PreloadModel',
                request_serializer=service__pb2.PreloadRequest.SerializeToString,
                response_deserializer=service__pb2.PreloadResponse.FromString,
                _registered_method=True)


class SearchEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SemanticSearch(self, request, context):
        """Executes a hybrid semantic and lexical search query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexTargetFolder(self, request, context):
        """Triggers background indexing of a specific directory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStatus(self, request, context):
        """Retrieves running status, total file counts, and vector counts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSettings(self, request, context):
        """Updates system settings dynamically (e.g. active model, exclusions)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreloadModel(self, request, context):
        """Preloads/downloads a model explicitly
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SemanticSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.SemanticSearch,
                    request_deserializer=service__pb2.SearchRequest.FromString,
                    response_serializer=service__pb2.SearchResponse.SerializeToString,
            ),
            'IndexTargetFolder': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexTargetFolder,
                    request_deserializer=service__pb2.IndexRequest.FromString,
                    response_serializer=service__pb2.IndexResponse.SerializeToString,
            ),
            'GetSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.StatusResponse.SerializeToString,
            ),
            'UpdateSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSettings,
                    request_deserializer=service__pb2.SettingsRequest.FromString,
                    response_serializer=service__pb2.SettingsResponse.SerializeToString,
            ),
            'PreloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.PreloadModel,
                    request_deserializer=service__pb2.PreloadRequest.FromString,
                    response_serializer=service__pb2.PreloadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swiftsearch.SearchEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swiftsearch.SearchEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SearchEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SemanticSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swiftsearch.SearchEngine/SemanticSearch',
            service__pb2.SearchRequest.SerializeToString,
            service__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IndexTargetFolder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swiftsearch.SearchEngine/IndexTargetFolder',
            service__pb2.IndexRequest.SerializeToString,
            service__pb2.IndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swiftsearch.SearchEngine/GetSystemStatus',
            service__pb2.Empty.SerializeToString,
            service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swiftsearch.SearchEngine/UpdateSettings',
            service__pb2.SettingsRequest.SerializeToString,
            service__pb2.SettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swiftsearch.SearchEngine/PreloadModel',
            service__pb2.PreloadRequest.SerializeToString,
            service__pb2.PreloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
