// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace SwiftSearch.Core.Protos {
  public static partial class SearchEngine
  {
    static readonly string __ServiceName = "swiftsearch.SearchEngine";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SwiftSearch.Core.Protos.SearchRequest> __Marshaller_swiftsearch_SearchRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SwiftSearch.Core.Protos.SearchRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SwiftSearch.Core.Protos.SearchResponse> __Marshaller_swiftsearch_SearchResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SwiftSearch.Core.Protos.SearchResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SwiftSearch.Core.Protos.IndexRequest> __Marshaller_swiftsearch_IndexRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SwiftSearch.Core.Protos.IndexRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SwiftSearch.Core.Protos.IndexResponse> __Marshaller_swiftsearch_IndexResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SwiftSearch.Core.Protos.IndexResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SwiftSearch.Core.Protos.Empty> __Marshaller_swiftsearch_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SwiftSearch.Core.Protos.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SwiftSearch.Core.Protos.StatusResponse> __Marshaller_swiftsearch_StatusResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SwiftSearch.Core.Protos.StatusResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SwiftSearch.Core.Protos.SettingsRequest> __Marshaller_swiftsearch_SettingsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SwiftSearch.Core.Protos.SettingsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SwiftSearch.Core.Protos.SettingsResponse> __Marshaller_swiftsearch_SettingsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SwiftSearch.Core.Protos.SettingsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SwiftSearch.Core.Protos.DownloadModelRequest> __Marshaller_swiftsearch_DownloadModelRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SwiftSearch.Core.Protos.DownloadModelRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SwiftSearch.Core.Protos.DownloadModelResponse> __Marshaller_swiftsearch_DownloadModelResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SwiftSearch.Core.Protos.DownloadModelResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::SwiftSearch.Core.Protos.SearchRequest, global::SwiftSearch.Core.Protos.SearchResponse> __Method_SemanticSearch = new grpc::Method<global::SwiftSearch.Core.Protos.SearchRequest, global::SwiftSearch.Core.Protos.SearchResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SemanticSearch",
        __Marshaller_swiftsearch_SearchRequest,
        __Marshaller_swiftsearch_SearchResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::SwiftSearch.Core.Protos.SearchRequest, global::SwiftSearch.Core.Protos.SearchResponse> __Method_EverythingSearch = new grpc::Method<global::SwiftSearch.Core.Protos.SearchRequest, global::SwiftSearch.Core.Protos.SearchResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "EverythingSearch",
        __Marshaller_swiftsearch_SearchRequest,
        __Marshaller_swiftsearch_SearchResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::SwiftSearch.Core.Protos.IndexRequest, global::SwiftSearch.Core.Protos.IndexResponse> __Method_IndexTargetFolder = new grpc::Method<global::SwiftSearch.Core.Protos.IndexRequest, global::SwiftSearch.Core.Protos.IndexResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "IndexTargetFolder",
        __Marshaller_swiftsearch_IndexRequest,
        __Marshaller_swiftsearch_IndexResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::SwiftSearch.Core.Protos.Empty, global::SwiftSearch.Core.Protos.StatusResponse> __Method_GetSystemStatus = new grpc::Method<global::SwiftSearch.Core.Protos.Empty, global::SwiftSearch.Core.Protos.StatusResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSystemStatus",
        __Marshaller_swiftsearch_Empty,
        __Marshaller_swiftsearch_StatusResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::SwiftSearch.Core.Protos.SettingsRequest, global::SwiftSearch.Core.Protos.SettingsResponse> __Method_UpdateSettings = new grpc::Method<global::SwiftSearch.Core.Protos.SettingsRequest, global::SwiftSearch.Core.Protos.SettingsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateSettings",
        __Marshaller_swiftsearch_SettingsRequest,
        __Marshaller_swiftsearch_SettingsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::SwiftSearch.Core.Protos.DownloadModelRequest, global::SwiftSearch.Core.Protos.DownloadModelResponse> __Method_DownloadModel = new grpc::Method<global::SwiftSearch.Core.Protos.DownloadModelRequest, global::SwiftSearch.Core.Protos.DownloadModelResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "DownloadModel",
        __Marshaller_swiftsearch_DownloadModelRequest,
        __Marshaller_swiftsearch_DownloadModelResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::SwiftSearch.Core.Protos.ServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SearchEngine</summary>
    [grpc::BindServiceMethod(typeof(SearchEngine), "BindService")]
    public abstract partial class SearchEngineBase
    {
      /// <summary>
      /// Executes a hybrid semantic and lexical search query
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::SwiftSearch.Core.Protos.SearchResponse> SemanticSearch(global::SwiftSearch.Core.Protos.SearchRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Executes an instant filename search using the Everything SDK
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::SwiftSearch.Core.Protos.SearchResponse> EverythingSearch(global::SwiftSearch.Core.Protos.SearchRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Triggers background indexing of a specific directory
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::SwiftSearch.Core.Protos.IndexResponse> IndexTargetFolder(global::SwiftSearch.Core.Protos.IndexRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Retrieves running status, total file counts, and vector counts
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::SwiftSearch.Core.Protos.StatusResponse> GetSystemStatus(global::SwiftSearch.Core.Protos.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Updates system settings dynamically (e.g. active model, exclusions)
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::SwiftSearch.Core.Protos.SettingsResponse> UpdateSettings(global::SwiftSearch.Core.Protos.SettingsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Starts downloading a model and returns a stream of download progress (0 to 100%)
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task DownloadModel(global::SwiftSearch.Core.Protos.DownloadModelRequest request, grpc::IServerStreamWriter<global::SwiftSearch.Core.Protos.DownloadModelResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SearchEngine</summary>
    public partial class SearchEngineClient : grpc::ClientBase<SearchEngineClient>
    {
      /// <summary>Creates a new client for SearchEngine</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public SearchEngineClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SearchEngine that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public SearchEngineClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected SearchEngineClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected SearchEngineClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Executes a hybrid semantic and lexical search query
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::SwiftSearch.Core.Protos.SearchResponse SemanticSearch(global::SwiftSearch.Core.Protos.SearchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SemanticSearch(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Executes a hybrid semantic and lexical search query
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::SwiftSearch.Core.Protos.SearchResponse SemanticSearch(global::SwiftSearch.Core.Protos.SearchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SemanticSearch, null, options, request);
      }
      /// <summary>
      /// Executes a hybrid semantic and lexical search query
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::SwiftSearch.Core.Protos.SearchResponse> SemanticSearchAsync(global::SwiftSearch.Core.Protos.SearchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SemanticSearchAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Executes a hybrid semantic and lexical search query
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::SwiftSearch.Core.Protos.SearchResponse> SemanticSearchAsync(global::SwiftSearch.Core.Protos.SearchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SemanticSearch, null, options, request);
      }
      /// <summary>
      /// Executes an instant filename search using the Everything SDK
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::SwiftSearch.Core.Protos.SearchResponse EverythingSearch(global::SwiftSearch.Core.Protos.SearchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EverythingSearch(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Executes an instant filename search using the Everything SDK
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::SwiftSearch.Core.Protos.SearchResponse EverythingSearch(global::SwiftSearch.Core.Protos.SearchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_EverythingSearch, null, options, request);
      }
      /// <summary>
      /// Executes an instant filename search using the Everything SDK
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::SwiftSearch.Core.Protos.SearchResponse> EverythingSearchAsync(global::SwiftSearch.Core.Protos.SearchRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EverythingSearchAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Executes an instant filename search using the Everything SDK
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::SwiftSearch.Core.Protos.SearchResponse> EverythingSearchAsync(global::SwiftSearch.Core.Protos.SearchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_EverythingSearch, null, options, request);
      }
      /// <summary>
      /// Triggers background indexing of a specific directory
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::SwiftSearch.Core.Protos.IndexResponse IndexTargetFolder(global::SwiftSearch.Core.Protos.IndexRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return IndexTargetFolder(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Triggers background indexing of a specific directory
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::SwiftSearch.Core.Protos.IndexResponse IndexTargetFolder(global::SwiftSearch.Core.Protos.IndexRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_IndexTargetFolder, null, options, request);
      }
      /// <summary>
      /// Triggers background indexing of a specific directory
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::SwiftSearch.Core.Protos.IndexResponse> IndexTargetFolderAsync(global::SwiftSearch.Core.Protos.IndexRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return IndexTargetFolderAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Triggers background indexing of a specific directory
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::SwiftSearch.Core.Protos.IndexResponse> IndexTargetFolderAsync(global::SwiftSearch.Core.Protos.IndexRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_IndexTargetFolder, null, options, request);
      }
      /// <summary>
      /// Retrieves running status, total file counts, and vector counts
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::SwiftSearch.Core.Protos.StatusResponse GetSystemStatus(global::SwiftSearch.Core.Protos.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSystemStatus(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieves running status, total file counts, and vector counts
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::SwiftSearch.Core.Protos.StatusResponse GetSystemStatus(global::SwiftSearch.Core.Protos.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSystemStatus, null, options, request);
      }
      /// <summary>
      /// Retrieves running status, total file counts, and vector counts
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::SwiftSearch.Core.Protos.StatusResponse> GetSystemStatusAsync(global::SwiftSearch.Core.Protos.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSystemStatusAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieves running status, total file counts, and vector counts
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::SwiftSearch.Core.Protos.StatusResponse> GetSystemStatusAsync(global::SwiftSearch.Core.Protos.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSystemStatus, null, options, request);
      }
      /// <summary>
      /// Updates system settings dynamically (e.g. active model, exclusions)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::SwiftSearch.Core.Protos.SettingsResponse UpdateSettings(global::SwiftSearch.Core.Protos.SettingsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateSettings(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Updates system settings dynamically (e.g. active model, exclusions)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::SwiftSearch.Core.Protos.SettingsResponse UpdateSettings(global::SwiftSearch.Core.Protos.SettingsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateSettings, null, options, request);
      }
      /// <summary>
      /// Updates system settings dynamically (e.g. active model, exclusions)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::SwiftSearch.Core.Protos.SettingsResponse> UpdateSettingsAsync(global::SwiftSearch.Core.Protos.SettingsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateSettingsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Updates system settings dynamically (e.g. active model, exclusions)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::SwiftSearch.Core.Protos.SettingsResponse> UpdateSettingsAsync(global::SwiftSearch.Core.Protos.SettingsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateSettings, null, options, request);
      }
      /// <summary>
      /// Starts downloading a model and returns a stream of download progress (0 to 100%)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::SwiftSearch.Core.Protos.DownloadModelResponse> DownloadModel(global::SwiftSearch.Core.Protos.DownloadModelRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DownloadModel(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Starts downloading a model and returns a stream of download progress (0 to 100%)
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::SwiftSearch.Core.Protos.DownloadModelResponse> DownloadModel(global::SwiftSearch.Core.Protos.DownloadModelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_DownloadModel, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override SearchEngineClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SearchEngineClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(SearchEngineBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SemanticSearch, serviceImpl.SemanticSearch)
          .AddMethod(__Method_EverythingSearch, serviceImpl.EverythingSearch)
          .AddMethod(__Method_IndexTargetFolder, serviceImpl.IndexTargetFolder)
          .AddMethod(__Method_GetSystemStatus, serviceImpl.GetSystemStatus)
          .AddMethod(__Method_UpdateSettings, serviceImpl.UpdateSettings)
          .AddMethod(__Method_DownloadModel, serviceImpl.DownloadModel).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SearchEngineBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SemanticSearch, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SwiftSearch.Core.Protos.SearchRequest, global::SwiftSearch.Core.Protos.SearchResponse>(serviceImpl.SemanticSearch));
      serviceBinder.AddMethod(__Method_EverythingSearch, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SwiftSearch.Core.Protos.SearchRequest, global::SwiftSearch.Core.Protos.SearchResponse>(serviceImpl.EverythingSearch));
      serviceBinder.AddMethod(__Method_IndexTargetFolder, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SwiftSearch.Core.Protos.IndexRequest, global::SwiftSearch.Core.Protos.IndexResponse>(serviceImpl.IndexTargetFolder));
      serviceBinder.AddMethod(__Method_GetSystemStatus, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SwiftSearch.Core.Protos.Empty, global::SwiftSearch.Core.Protos.StatusResponse>(serviceImpl.GetSystemStatus));
      serviceBinder.AddMethod(__Method_UpdateSettings, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SwiftSearch.Core.Protos.SettingsRequest, global::SwiftSearch.Core.Protos.SettingsResponse>(serviceImpl.UpdateSettings));
      serviceBinder.AddMethod(__Method_DownloadModel, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::SwiftSearch.Core.Protos.DownloadModelRequest, global::SwiftSearch.Core.Protos.DownloadModelResponse>(serviceImpl.DownloadModel));
    }

  }
}
#endregion
